var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ", 
   "                                                                                ",
   "                                                                                ", 
   "                                                                                ",
   "                        yyyyyyyyyy                                              ",
   "                   yyyyyyyyyy                                                   ",
   "                 yyyyyyyyyyyy                     oooo                          ",
   "                                                                                ",
   "                                                   xxxxxxxxxxxxxx               ",
   "   @                                                                            ",
   " xxxxxx           xxxxxxx                                                       ",
   "      x           x                                                             ",
   "      x!!!!!!!!!!!x                         k k                                 ",
   "      x!!!!!!!!!!!x                   xxxxxxxxxxxxxxxx                          ",
   "      x!!!!!!!!!!!x                                                ddd          ",
   "      x!!!!!!!!!!!x                                                ddd          ",
   "      x!!!!!!!!!!!x                                                ddd   oooo   ",
   "      xxxxxxxxxxxxxxxxxxxxxxx                                   xxxxxxxxxxxxxxxx",
   "                            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               ",
   "                            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               ",
   "                            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               ",
   "                            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               ",
   "                            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x               ",
   "                            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx               ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                   oo                             ", 
   "                                                                                 xxxxxx                           ",
   "                                                      xxxxxxxxx                o xvvvvx  o                        ",
   "                                                                              xxxxvvvvxxxxx                       ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                         xxxxx        xxxxxxxxx                 xxxxxxxxx                                         ",
   "                                                                                                                  ",
   "     @                                                                        o o     ooo              ooooo      ",
   "xxxxxxxxxxxxxxxxxxx                                                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                           ",
   "                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                           ",
   "                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                           ",
   "                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                           ",
   "                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                           ",
   "                  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                                           ",
   "                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                           ",
   "                                                                                                                  ",
   "                                                                                                                  "],
  ["                                                                                                              ",
   "                                                             o                                                ",
   "                                                           oxxxo                                              ",
   "                                                          xxxvxxx                                             ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                   ooo            ooo                                         ",
   "                                                   xxxxxxxxxxxxxxxxxx                                         ",
   "                                                 xxx                                                          ",
   "                       o                                                                                      ",
   "                     xxxxxx                                                                                   ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                         o                                                                    ",
   "                                    xxxxxxxx                                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                      o                                                                                       ",
   "                  xxxxxxxx                                                                                    ",
   "                                                                                                              ",
   "                                                                                                              ",
   "    @                                                                           ooo                           ",
   "xxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "               x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "               xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!"],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
